appName = "transformer"

[mysql.default]
host = "127.0.0.1"
port = 3306
user = "root"
pass = "123456"
database = "transformer"
charset = "utf8mb4"
collation = "utf8mb4_general_ci"
maxidleconns = 10
maxopenconns = 100
connmaxlifetime = 60

[mysql.write]
host = "127.0.0.1"
port = 3306
user = "root"
pass = "123456"
database = "transformer"
charset = "utf8mb4"
collation = "utf8mb4_general_ci"
maxidleconns = 10
maxopenconns = 100
connmaxlifetime = 60

[redis.default]
host = "127.0.0.1"
port = 6379
database = 0
pass = ""

[redis.queue]
host = "127.0.0.1"
port = 6379
database = 0
pass = ""

[log]
level = "debug"
path = "storage/logs"
maxSize = 5
maxAge = 30
maxBackup = 5
localTime = true
compress = true
